Repository Elusive789/Hacktober2022, pull requests merged in 2022-10, with the labels that each got.

#1 Create askpy quiz
  askpy quiz
Labels: good first issue, hacktoberfest-accepted

#4 Create donneeee
  donneeee
Labels: enhancement, hacktoberfest-accepted

#3 Create beginner-friendly
  beginner-friendly
Labels: hacktoberfest-accepted

#9 Create #rules
  #rules
Labels: enhancement, hacktoberfest-accepted

#8 Update Contributers.md
  Contributers.md
Labels: hacktoberfest-accepted

#7 Create hacktober 2022
  hacktober 2022
Labels: hacktoberfest-accepted

#6 Create # Simple pygame program
  # Simple pygame program
Labels: hacktoberfest-accepted
